### ISSUE TITLE
Recover plot operators

### ISSUE THREAD

**Issue by andreab1997** [N3PDF/eko#80] opened 2021-11-19 15:09 UTC
Not correct plotting of operators when benchmarking using sandbox. The generated pdf file has lot of blank pages and some of the plotted values are NaN. 

**Reproduce**
1. change `plot_operator`  to `True`  in `sandbox.py` 
2. Run `python sandbox.py`
3. Look to the output in  ...eko/benchmarks/data/apfel_bench/

**Comment by AleCandido** [comment] 2021-11-19 15:27
Please, can you add some details and how to reproduce?

**Comment by andreab1997** [comment] 2021-11-22 14:59
@AleCandido Since we found the problem and changed the colormap, I think we can close this issue, right?

**Comment by AleCandido** [comment] 2021-11-22 15:21
I think so as well :)

Maybe last thing is: check how they look like in evolution space (in principle should be much easier, since you should only have relevant elements for `S.S, S.g, g.S, g.g, T3.T3, V3.V3, ...`, and not the full square).

**Comment by AleCandido** [comment] 2021-11-22 15:22
> Maybe last thing is: check how they look like in evolution space (in principle should be much easier, since you should only have relevant elements for `S.S, S.g, g.S, g.g, T3.T3, V3.V3, ...`, and not the full square).

Most likely it won't happen, because the operator is computed before in flavor space. A possible solution is to introduce some kind of tolerance when checking the absolute maximum, and ignore operators that have all elements below.

**Comment by andreab1997** [comment] 2021-11-22 15:49
> > Maybe last thing is: check how they look like in evolution space (in principle should be much easier, since you should only have relevant elements for `S.S, S.g, g.S, g.g, T3.T3, V3.V3, ...`, and not the full square).
> 
> Most likely it won't happen, because the operator is computed before in flavor space. A possible solution is to introduce some kind of tolerance when checking the absolute maximum, and ignore operators that have all elements below.

Problem is that I noticed now that plots.py only plots on pid labels. So first I need to change this

**Comment by andreab1997** [comment] 2021-11-23 12:53
> Ok, good to have found out.

Now the plots in evolution basis should be available. However, I found another bug. When you run sandbox in flavor_basis it will not work. Speaking to @felixhekhorn, he said that it is related to how the caching is done and that it is a known bug. So, should I close this issue @AleCandido?

**Comment by AleCandido** [comment] 2021-11-23 15:26
Thank you very much for your progresses @andreab1997, about the two points:

- before closing the issue, I'd like to see the plots in evolution basis, if they are fine I'd be happy to actually close (for the sake of speed, and by the way reporting, can you post a PDF in a comment in this issue, please?)
- concerning the `flavor_basis` I don't perfectly remember the issue, but I've an idea, and I agree that is a completely decoupled problem, so, if ever, we'll open a separate issue

**Comment by andreab1997** [comment] 2021-11-23 15:40
> 

Yes, I post here the PDF with the plot in ev.basis
[off080e_tedfbed.pdf](https://github.com/N3PDF/eko/files/7589240/off080e_tedfbed.pdf)

**Comment by AleCandido** [comment] 2021-11-23 15:53
You see that some are not worth to plot, like `V3.V`:

![Screenshot from 2021-11-23 16-47-37](https://user-images.githubusercontent.com/10830876/143057059-518ca01c-9119-4759-baa1-bbd951e8e772.png)

because it's fully non-singlet and non-diagonal, but also `V.g`:
![Screenshot from 2021-11-23 16-48-31](https://user-images.githubusercontent.com/10830876/143057275-999d2579-468a-48f3-9fbe-2a57143f6ecf.png)

that looks much smoother, it's still not worth, if you look at the scale.

So I would filter them out putting a threshold, maybe at `10^-8`.
Moreover, try to translate the names according to the map in `basis_rotations`, since these flavors code we made up ourselves and are little understandable to anyone else (at the moment they are not even present in the docs...).

**Comment by andreab1997** [comment] 2021-11-23 16:43
> You see that some are not worth to plot, like `V3.V`:
> 
> ![Screenshot from 2021-11-23 16-47-37](https://user-images.githubusercontent.com/10830876/143057059-518ca01c-9119-4759-baa1-bbd951e8e772.png)
> 
> because it's fully non-singlet and non-diagonal, but also `V.g`: ![Screenshot from 2021-11-23 16-48-31](https://user-images.githubusercontent.com/10830876/143057275-999d2579-468a-48f3-9fbe-2a57143f6ecf.png)
> 
> that looks much smoother, it's still not worth, if you look at the scale.
> 
> So I would filter them out putting a threshold, maybe at `10^-8`. Moreover, try to translate the names according to the map in `basis_rotations`, since these flavors code we made up ourselves and are little understandable to anyone else (at the moment they are not even present in the docs...).

Yes, sorry you had already mentioned the threshold stuff. Anyway, now it should work. I'm posting the new pdf. 
[off080e_tedfbed.pdf](https://github.com/N3PDF/eko/files/7589677/off080e_tedfbed.pdf)

**Comment by AleCandido** [comment] 2021-11-23 21:36
> Yes, sorry you had already mentioned the threshold stuff. Anyway, now it should work. I'm posting the new pdf.

Don't mind, that's exactly how the old plots looked like, and it's perfectly recovered.

Thank you for your effort, I think we can close!

**Comment by giacomomagni** [comment] 2021-11-24 08:18
Hi guys, sorry for stepping in, I have a naive question, why in the op plots the last grid points (bottom right corner) are not a triangular matrix... I see they contain small values, but they shouldn't be there at all no?
If not too much, it will be nice to rescale the axes in the range [x_min, 1] instead of the grid binning

**Comment by AleCandido** [comment] 2021-11-24 09:45
> Hi guys, sorry for stepping in, I have a naive question, why in the op plots the last grid points (bottom right corner) are not a triangular matrix... I see they contain small values, but they shouldn't be there at all no?

It's a relevant question, and you have to add that last row is also empty, but we have answers for this (and at least the second one you should know, since you implemented yourself):
- it's not triangular because of interpolation, you need at least that many points (`interpolation_degree + 1`)
- last row is empty, because the PDF it's constrained to be 0 at z=1 `f(z=1) = 0`, thus it is completely independent from the input (nevertheless it's nice to have square operators, and it's not a huge waste to add one line, while it would be harder to maintain to have a rectangular operator and having to add one point manually to the output PDF)

**Comment by AleCandido** [comment] 2021-11-24 09:46
>  If not too much, it will be nice to rescale the axes in the range [x_min, 1] instead of the grid binning

I guess you are speaking of relabeling the axes (that's feasible) with z values (I keep calling z, you know why), but bins are bins (those are matrix entries), so I would keep the binning explicit (even in the relabeled variable)

**Comment by giacomomagni** [comment] 2022-05-11 06:51
This has been solved right?

**Comment by AleCandido** [comment] 2022-05-11 06:58
I guess so. @andreab1997?

**Comment by andreab1997** [comment] 2022-05-11 07:12
> I guess so. @andreab1997?

Yes, it is solved.

**Closed** 2022-05-11 07:20 UTC
Labels: bug
